// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_Omega
arma::mat compute_Omega(int TT, double lGP_tau2_omega, double lGP_sigma2_omega);
RcppExport SEXP _bSCDCsampler_compute_Omega(SEXP TTSEXP, SEXP lGP_tau2_omegaSEXP, SEXP lGP_sigma2_omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< double >::type lGP_tau2_omega(lGP_tau2_omegaSEXP);
    Rcpp::traits::input_parameter< double >::type lGP_sigma2_omega(lGP_sigma2_omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Omega(TT, lGP_tau2_omega, lGP_sigma2_omega));
    return rcpp_result_gen;
END_RCPP
}
// compute_Sigma
arma::mat compute_Sigma(arma::mat loc, double theta);
RcppExport SEXP _bSCDCsampler_compute_Sigma(SEXP locSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type loc(locSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Sigma(loc, theta));
    return rcpp_result_gen;
END_RCPP
}
// calcium_gibbsCPP_burnin
Rcpp::List calcium_gibbsCPP_burnin(int Nrep, int burnin, arma::mat Y, arma::mat loc, double par_varcov_loc, arma::vec cluster_signal_start, int max_cl, double b_start, double gamma_start, double sigma2_start, double tau2_start, arma::mat cluster_amplitudes_start, arma::vec ak_start, double varC0, double hyp_a1, double hyp_a2, double hyp_b1, double hyp_b2, double hyp_sigma21, double hyp_sigma22, double hyp_tau21, double hyp_tau22, double hyp_gamma1, double hyp_gamma2, double eps_gamma, double step_AMH_gamma, double eps_a, double step_AMH_a, double a_low, double lGP_tau2_omega, double lGP_sigma2_omega, double lGP_error_variance, double mu_alpha, double sigma2_alpha);
RcppExport SEXP _bSCDCsampler_calcium_gibbsCPP_burnin(SEXP NrepSEXP, SEXP burninSEXP, SEXP YSEXP, SEXP locSEXP, SEXP par_varcov_locSEXP, SEXP cluster_signal_startSEXP, SEXP max_clSEXP, SEXP b_startSEXP, SEXP gamma_startSEXP, SEXP sigma2_startSEXP, SEXP tau2_startSEXP, SEXP cluster_amplitudes_startSEXP, SEXP ak_startSEXP, SEXP varC0SEXP, SEXP hyp_a1SEXP, SEXP hyp_a2SEXP, SEXP hyp_b1SEXP, SEXP hyp_b2SEXP, SEXP hyp_sigma21SEXP, SEXP hyp_sigma22SEXP, SEXP hyp_tau21SEXP, SEXP hyp_tau22SEXP, SEXP hyp_gamma1SEXP, SEXP hyp_gamma2SEXP, SEXP eps_gammaSEXP, SEXP step_AMH_gammaSEXP, SEXP eps_aSEXP, SEXP step_AMH_aSEXP, SEXP a_lowSEXP, SEXP lGP_tau2_omegaSEXP, SEXP lGP_sigma2_omegaSEXP, SEXP lGP_error_varianceSEXP, SEXP mu_alphaSEXP, SEXP sigma2_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type Nrep(NrepSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type loc(locSEXP);
    Rcpp::traits::input_parameter< double >::type par_varcov_loc(par_varcov_locSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cluster_signal_start(cluster_signal_startSEXP);
    Rcpp::traits::input_parameter< int >::type max_cl(max_clSEXP);
    Rcpp::traits::input_parameter< double >::type b_start(b_startSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_start(gamma_startSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_start(sigma2_startSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_start(tau2_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cluster_amplitudes_start(cluster_amplitudes_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ak_start(ak_startSEXP);
    Rcpp::traits::input_parameter< double >::type varC0(varC0SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_a1(hyp_a1SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_a2(hyp_a2SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_b1(hyp_b1SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_b2(hyp_b2SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_sigma21(hyp_sigma21SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_sigma22(hyp_sigma22SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_tau21(hyp_tau21SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_tau22(hyp_tau22SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_gamma1(hyp_gamma1SEXP);
    Rcpp::traits::input_parameter< double >::type hyp_gamma2(hyp_gamma2SEXP);
    Rcpp::traits::input_parameter< double >::type eps_gamma(eps_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type step_AMH_gamma(step_AMH_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps_a(eps_aSEXP);
    Rcpp::traits::input_parameter< double >::type step_AMH_a(step_AMH_aSEXP);
    Rcpp::traits::input_parameter< double >::type a_low(a_lowSEXP);
    Rcpp::traits::input_parameter< double >::type lGP_tau2_omega(lGP_tau2_omegaSEXP);
    Rcpp::traits::input_parameter< double >::type lGP_sigma2_omega(lGP_sigma2_omegaSEXP);
    Rcpp::traits::input_parameter< double >::type lGP_error_variance(lGP_error_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type mu_alpha(mu_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_alpha(sigma2_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(calcium_gibbsCPP_burnin(Nrep, burnin, Y, loc, par_varcov_loc, cluster_signal_start, max_cl, b_start, gamma_start, sigma2_start, tau2_start, cluster_amplitudes_start, ak_start, varC0, hyp_a1, hyp_a2, hyp_b1, hyp_b2, hyp_sigma21, hyp_sigma22, hyp_tau21, hyp_tau22, hyp_gamma1, hyp_gamma2, eps_gamma, step_AMH_gamma, eps_a, step_AMH_a, a_low, lGP_tau2_omega, lGP_sigma2_omega, lGP_error_variance, mu_alpha, sigma2_alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bSCDCsampler_compute_Omega", (DL_FUNC) &_bSCDCsampler_compute_Omega, 3},
    {"_bSCDCsampler_compute_Sigma", (DL_FUNC) &_bSCDCsampler_compute_Sigma, 2},
    {"_bSCDCsampler_calcium_gibbsCPP_burnin", (DL_FUNC) &_bSCDCsampler_calcium_gibbsCPP_burnin, 34},
    {NULL, NULL, 0}
};

RcppExport void R_init_bSCDCsampler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
