# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Omega <- function(TT, lGP_tau2_omega, lGP_sigma2_omega) {
    .Call('_bSCDCsampler_compute_Omega', PACKAGE = 'bSCDCsampler', TT, lGP_tau2_omega, lGP_sigma2_omega)
}

compute_Sigma <- function(loc, theta) {
    .Call('_bSCDCsampler_compute_Sigma', PACKAGE = 'bSCDCsampler', loc, theta)
}

calcium_gibbsCPP_burnin <- function(Nrep, burnin, Y, loc, par_varcov_loc, cluster_signal_start, max_cl, b_start, gamma_start, sigma2_start, tau2_start, cluster_amplitudes_start, ak_start, varC0, hyp_a1, hyp_a2, hyp_b1, hyp_b2, hyp_sigma21, hyp_sigma22, hyp_tau21, hyp_tau22, hyp_gamma1, hyp_gamma2, eps_gamma, step_AMH_gamma, eps_a, step_AMH_a, a_low, lGP_tau2_omega, lGP_sigma2_omega, lGP_error_variance, mu_alpha, sigma2_alpha) {
    .Call('_bSCDCsampler_calcium_gibbsCPP_burnin', PACKAGE = 'bSCDCsampler', Nrep, burnin, Y, loc, par_varcov_loc, cluster_signal_start, max_cl, b_start, gamma_start, sigma2_start, tau2_start, cluster_amplitudes_start, ak_start, varC0, hyp_a1, hyp_a2, hyp_b1, hyp_b2, hyp_sigma21, hyp_sigma22, hyp_tau21, hyp_tau22, hyp_gamma1, hyp_gamma2, eps_gamma, step_AMH_gamma, eps_a, step_AMH_a, a_low, lGP_tau2_omega, lGP_sigma2_omega, lGP_error_variance, mu_alpha, sigma2_alpha)
}

