#' @import Rcpp
#' @export 
#' @useDynLib bSCDCsampler
calcium_gibbs_burnin = function( Nrep, 
                                burnin,
                                Y, 
                                loc,
                                par_varcov_loc, 
                                cluster_signal_start,
                                max_cl,
                                b_start, gamma_start, 
                                sigma2_start, 
                                tau2_start,
                                cluster_amplitudes_start,
                                ak_start,
                                varC0, 
                                hyp_a1, hyp_a2, 
                                hyp_b1, hyp_b2, 
                                hyp_sigma21, hyp_sigma22, 
                                hyp_tau21, hyp_tau22, 
                                hyp_gamma1, hyp_gamma2, 
                                eps_gamma,step_AMH_gamma,
                                eps_a, step_AMH_a, a_low=0,
                                lGP_tau2_omega, 
                                lGP_sigma2_omega, 
                                lGP_error_variance, 
                                mu_alpha,
                                sigma2_alpha
) 
{
  out = calcium_gibbsCPP_burnin( Nrep,
                                burnin,
                                Y, 
                                loc, 
                                par_varcov_loc,
                                cluster_signal_start,
                                max_cl,
                                b_start, gamma_start, 
                                sigma2_start, 
                                tau2_start,
                                cluster_amplitudes_start,
                                ak_start,
                                varC0, 
                                hyp_a1, hyp_a2, 
                                hyp_b1, hyp_b2, 
                                hyp_sigma21, hyp_sigma22, 
                                hyp_tau21, hyp_tau22, 
                                hyp_gamma1, hyp_gamma2, 
                                eps_gamma,
                                step_AMH_gamma,
                                eps_a,
                                step_AMH_a, 
                                a_low,
                                lGP_tau2_omega, 
                                lGP_sigma2_omega, 
                                lGP_error_variance, 
                                mu_alpha,
                                sigma2_alpha
        ) 
  return( out )
}
